### ISSUE TITLE
Implement quantum circuits in frontend

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#22]
We could use https://quantumjavascript.app/Q-Circuit.html

**Comment by nelimee** [comment]
The textual output format seems like something sufficient to construct the corresponding quantum circuit in the Python code. 
There is still a question on detectors and how they should be implemented, but this package seems to be sufficient to handle at least the quantum circuit part.

**Comment by smburdick** [comment]
I think this is part of tasks 4+.

**Comment by Gistbatch** [comment]
Could we look at [qni](https://github.com/qniapp/qni) instead? It's based on Quirk and at least has a npm package available.
I was interested in doing this task, but I would need some pointers on how to include any of the alternatives.
As I see it `q.js` is pure javascript and renders `div` elements; `qni` uses typescript to render `svg` elements.
For a quick solution it would be fine to use one of those, but wouldn't it make more sense to use a pixy for this?
Especially since we don't need the simulation capabilities, and we could also define the output based on our needs

**Comment by smburdick** [comment]
> Could we look at [qni](https://github.com/qniapp/qni) instead? It's based on Quirk and at least has a npm package available. I was interested in doing this task, but I would need some pointers on how to include any of the alternatives. As I see it `q.js` is pure javascript and renders `div` elements; `qni` uses typescript to render `svg` elements. For a quick solution it would be fine to use one of those, but wouldn't it make more sense to use a pixy for this? Especially since we don't need the simulation capabilities, and we could also define the output based on our needs

@Gistbatch my intuition is that we could treat `qni` as a sub-module within the frontend code and invoke whichever components we need on-demand. React and Pixi already provide the HTML components, so we'd only need to invoke `qni`'s logic through JavaScript.

**Comment by smburdick** [comment]
Marking as redundant
