### ISSUE TITLE
Cannot delete cloned plaquette, _geometry becomes null pointer

### ISSUE THREAD

**Issue by smburdick** [QCHackers/tqec#24]
https://github.com/QCHackers/tqec/assets/16883876/814b91fc-2f7f-4cd7-8941-85fb9c377238

**Comment by rryoung98** [comment]
#29 is a duplicate so closing

**Comment by rryoung98** [comment]
In the initalizeClearButton() this.destroy() is called which is dangerous.

If the subchild plaquette does not have graphic associated with itself, there is a possibility that the clearing functionality will crash the app.

TypeError: this._geometry is null

**Comment by smburdick** [comment]
I saw that error too when testing the app. I will self assign this and start looking for reworks.

**Comment by smburdick** [comment]
Working in this branch: https://github.com/smburdick/tqec/tree/delete-cloned-plaquettes

I am able to delete plaquettes that I want. However, when I deselect and re-select a plaquette, and try to delete it, I get the error (paste -- https://pastebin.com/8eiL5tXz)

Here is a video showing what I mean.


https://github.com/QCHackers/tqec/assets/16883876/48c23735-cc58-4767-be23-8eb6d0c539aa

**Comment by rryoung98** [comment]
Yea I can speak more to the hunches I have for this issue. 

The issue we are facing is that calling destroy on the graphic is a code smell and a big no no. 

Here are some suggestions to fix it:

1. we can spin out the control panel for each plaquette into a plaquettecontrolpanel that is a child of the `workspace` container. When clicked on, the panel will find the plaquette that has been clicked on by using `getChildByName()`  builtin function. It may be necessary to traverse the entire child tree.  
2. We can also check that the cloning of plaquettes also does not add the plaquette graphic to another plaquette. Instead it should add the plaquette to a template.
3. when the current control panel is opened, another issue is that you can still double click on another plaquette and open the control panel for both plauqettes. This may be causing the .geometry issue as well since if we destroyed  a parent plaquette then the children will also be destroyed.

Let me know if that makes sense

**Comment by smburdick** [comment]
@rryoung98 I think point (1) resonated with me most. Because each plaquette can be manipulated individually, we can make each plaquette a child of the workspace container. I am concerned about how plaquettes are structured together into a larger surface code, which could mean that if a single plaquette was deleted, the structure representing the surface code would need to be updated as well.

>  It may be necessary to traverse the entire child tree.

JS objects (being hash tables) imply this can be done in O(1) time, amortized, so I don't think that's something to worry about.

I believe (2) (or something to that effect) is happening in the code already, as copy-dragging causes lots of plaquettes to spawn

I haven't noticed point (3). Do you mean that the control panels are stacked on top of each other?

**Comment by rryoung98** [comment]
yes for (3) i meant the stacking on top of each other which can further confuse the debugging experience (which plaquette it's clicking on).

(1) That's a good point w.r.t. are structured together into a larger surface code which is why figuring out the template is also important!

**Comment by smburdick** [comment]
@rryoung98 Regarding point (1): does this line in `createNewPlaquette()` do the trick?

```js
this.parent.addChild(newPlaquette);
```

[Context]( https://github.com/smburdick/tqec/blob/a73037ef3c70ef76500fb898ecb57bbd7ffa3730/tqecjs/src/workspace/plaquettes/PlaquetteClass.js#L331C1-L332C1)

**Comment by smburdick** [comment]
I reread your comment and understand your point about control panels (as distinct from plaquettes) better now. Will work on that too.

**Comment by smburdick** [comment]
I think PR #31 addresses this; any smaller issues can be spun off.
