### ISSUE TITLE
Include a cleaned up SketchUp template file

### ISSUE THREAD

**Issue by nelimee** [QCHackers/tqec#269]
**Is your feature request related to a problem? Please describe.**
The current SketchUp file we are using to store blocks contains some internal inconsistencies that make it impossible to use with the code developed in #261.

**Describe the solution you'd like**
Include in the repository one `.dae` file that will include all the blocks we might need, using a pre-defined and documented standard (RGB convention). This template file could then be updated whenever a new block is needed.

**Comment by inmzhang** [comment]
Hi Kabir @KabirDubey, you mentioned you could handle this task, so I have assigned it to you. Feel free to unassign yourself if needed.

**Comment by inmzhang** [comment]
To test importing the dae file exported from SketchUp, I included a cleaned template file and cleaned example CNOT file in #285(under directory https://github.com/QCHackers/tqec/tree/sketchup/notebooks/assets). I think there is no more issue about this, but @KabirDubey may double-check it.

**Comment by nelimee** [comment]
A few questions:
- how should we open such files? The extension is `.skp` instead of the usual `.dae`?
- where can I find the `.skp` file format?

**Comment by inmzhang** [comment]
Currently I can only view the `.dae` file with the help of some online dae viewer like [this one](https://imagetostl.com/view-dae-online), or import the `.dae` file into SketchUp. I'm trying to implement the code to display a Collada model interactively in the jupyter notebook context with embedded html using `three.js`, but not complete yet.

And `.skp` is the proprietary file type for SketchUp so we cannot really get the specification for it. We can open it directly in SketchUp or online at https://app.sketchup.com/app.

For our purpose, what we need is actually a single `exportable_template.skp`. Start from that, build the model in SketchUp and export the model as a `.dae` file. Then we can read the `.dae` with `tqec` and compile the structures down to the stim circuits.

**Comment by nelimee** [comment]
> I'm trying to implement the code to display a Collada model interactively in the jupyter notebook context with embedded html using `three.js`, but not complete yet.

Neat! Can't wait to see that!

Thanks for the explanations about the `.skp` file format. I agree with the current workflow then.

**Comment by KabirDubey** [comment]
> To test importing the dae file exported from SketchUp, I included a cleaned template file and cleaned example CNOT file in #285(under directory https://github.com/QCHackers/tqec/tree/sketchup/notebooks/assets). I think there is no more issue about this, but @KabirDubey may double-check it.

I get a file type error when I open `cleaned_export_cnot.skp` and `cleaned_exportable_template.skp` in SketchUp. I can import `cleaned_exportable_cnot.dae` and look at it fine. Can you export `cleaned_export_cnot.skp` to a `.dae` file and provide it so I can locally import it to my SketchUp and double-check?

One explanation for why I can't read your `.skp` files may be that we are using different SketchUp versions. My SketchUp version is [this old Windows freeware version](https://google-sketchup.en.lo4d.com/download) linked in the 6/19 slides. If I compare the unicode of your cleaned template SketchUp file side by side with the one that Austin provides in the Google drive (which I can open fine), there does seem to be a difference:

![unicode-differences](https://github.com/user-attachments/assets/90e08647-4c51-4c53-957a-5beee2e966ac)

Thank you for working on this BTW. I'm transferring from my old Windows to a new Mac so I'm working a bit slowly at the moment. 

> Start from that, build the model in SketchUp and export the model as a .dae file. 

The [6/19 slides](https://docs.google.com/presentation/d/1Ovnmb58ZwsaaFMgIX9Tuvq4BcDJBlkZ5eUX1VXJ4SKU/edit?pli=1#slide=id.g273d4f70c2f_0_55) say to focus on the Windows freeware SketchUp version because it supports exporting to `.dae`. Does this mean that SketchUp on Mac does not have this feature?

**Comment by inmzhang** [comment]
Hi Kabir, thanks for checking that! And I did not realize these issues.

I used a newer version of SketchUp to create the `.skp` files and did not test them with older versions. However, I can open the `.skp` file provided by Austin, which I believe was created with SketchUp version 8.0.16846. With that in mind, to ensure compatibility across multiple versions of SketchUp, we need to provide the `.skp` file in the oldest version available, which in our case is the free version 8.0.16846 on Windows.

Fortunately, as you have tested, the `.dae` file format works correctly with different SketchUp versions. Therefore, we should deliver `.dae` files instead of `.skp`.

> Does this mean that SketchUp on Mac does not have this feature?

As far as I know, almost all versions of SketchUp support `.dae` import/export. So, it's not a problem. Austin suggested we focus on the Windows freeware version of SketchUp only because it is free.

I will delete the `.skp` included in the assets and add a `cleaned_exportable_templates.dae` accordingly.

**Comment by inmzhang** [comment]
I have updated the files accordingly. @KabirDubey, would you mind checking that again?

**Comment by KabirDubey** [comment]
> I have updated the files accordingly. @KabirDubey, would you mind checking that again?

I can open both files in SketchUp, but I'm unable to see if the components are defined correctly. In the component library, there is only one component for the entire diagram. 

The `cleaned_exportable_cnot.skp` diagram gives:
![one-comp-1](https://github.com/user-attachments/assets/769285a9-5368-4088-8005-588c3a4be22a)

and likewise the `cleaned_exportable_tempalte.skp` diagram gives:
![one-comp-2](https://github.com/user-attachments/assets/a62fd326-d2c1-4c6d-88cf-b315da9d191c)

The way that I am viewing these components is Window > Component > the home icon, which works effectively for both the SketchUp files Austin provided and the ones you constructed from scratch in the backend last week. This seems like the issue where we lose our component data when we do a round trip of importing and exporting `.dae` files via SketchUp. 

To work around checking each component by inspecting the SketchUp diagram, I attempt to see if the backend can read the attributes of the CNOT you constructed with the cleaned template (just like you do in the demo notebook). This yields the following data level error:

![readable-cnot-error](https://github.com/user-attachments/assets/269cde7b-171a-4643-b821-bad391ac9b9a)

I haven't checked if the `from_dae_file` method has changed--this may be the source of the problem.

**Comment by inmzhang** [comment]
Hi Kabir, thanks for checking that.

> I can open both files in SketchUp, but I'm unable to see if the components are defined correctly. In the component library, there is only one component for the entire diagram.

Importing `.dae` files into SketchUp will not retain the components information as expected, but `.skp` files should work correctly. On my machine, I have no problem with the `clean_exportable_template.skp` and `clean_exportable_cnot.skp`, all the components shown in the window correctly. And I tested them with the online version of SketchUp, it worked as well...

> I haven't checked if the from_dae_file method has changed--this may be the source of the problem.

The source problem should be that you are using the `assets/cleaned_exportable_cnot.dae`, which is the one exported with a newer version of SketchUp. After the last commit, it should have been replace with https://github.com/QCHackers/tqec/blob/sketchup/notebooks/assets/clean_exportable_cnot.dae.

Once #285 is merged, the `SketchUpModel` class will be replaced with `BlockGraph` and the construction logic will be changed. Please refer to #285 for the details.
